# Generated by Django 2.1.3 on 2018-12-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsfile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
