# Generated by Django 2.1.3 on 2018-12-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0002_auto_20181222_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='users_file')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.RenameField(
            model_name='productsfile',
            old_name='specifications',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='productsfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
