# Generated by Django 2.1.3 on 2018-12-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0004_auto_20181222_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaiyiUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='加入日期')),
                ('end_date', models.DateTimeField(verbose_name='会员截止')),
                ('active', models.BooleanField(default=False, verbose_name='激活')),
                ('open_id', models.TextField(verbose_name='Open Id')),
                ('name', models.TextField(verbose_name='名字')),
                ('account_id', models.TextField(blank=True, null=True, verbose_name='微信号')),
            ],
        ),
        migrations.DeleteModel(
            name='UsersFile',
        ),
        migrations.AlterField(
            model_name='productsfile',
            name='file',
            field=models.FileField(upload_to='upload/', verbose_name='批量文件'),
        ),
        migrations.AlterField(
            model_name='productsfile',
            name='products_count',
            field=models.IntegerField(default=0, verbose_name='商品总数'),
        ),
        migrations.AlterField(
            model_name='productsfile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
