# Generated by Django 2.1.3 on 2019-01-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0005_auto_20181222_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsfile',
            name='wrong_rows',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
