# Generated by Django 2.1.4 on 2018-12-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0006_productsfile_wrong_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsfile',
            name='wrong_rows',
            field=models.URLField(default='', max_length=256, null=True),
        ),
    ]
