# Generated by Django 2.2 on 2019-04-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0006_productsfile_wrong_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='AInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='库存数量')),
                ('actual_cost', models.FloatField(null=True, verbose_name='实际成本')),
                ('market_cost', models.FloatField(null=True, verbose_name='市场成本')),
                ('price_3w', models.FloatField(null=True, verbose_name='3w零售价')),
                ('price_1w', models.FloatField(null=True, verbose_name='1w零售价')),
                ('price_retail', models.FloatField(null=True, verbose_name='零售价格')),
                ('hot_sell_degree', models.CharField(max_length=10, null=True, verbose_name='热卖程度')),
                ('buy_difficulty', models.CharField(max_length=10, null=True, verbose_name='采购难度')),
            ],
        ),
        migrations.CreateModel(
            name='BInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('market_cost_price', models.FloatField(null=True, verbose_name='市场成本')),
                ('cust_clear_free', models.FloatField(null=True, verbose_name='清关费用')),
                ('vip_price', models.TextField(null=True, verbose_name='活动特价')),
                ('customer_message', models.TextField(null=True, verbose_name='客户留言')),
                ('product_hk_info', models.TextField(null=True, verbose_name='刷货到香港返点信息')),
                ('dutyfree_storeprice', models.FloatField(null=True, verbose_name='免税店价格')),
                ('hot_sell_product', models.TextField(null=True, verbose_name='热卖款')),
                ('findpro_help', models.TextField(null=True, verbose_name='帮助找货')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(verbose_name='商品来源')),
                ('category', models.TextField(verbose_name='商品类型')),
                ('name', models.TextField(verbose_name='商品名称')),
                ('price', models.TextField(verbose_name='商品价格')),
                ('brief', models.TextField(verbose_name='商品简介')),
                ('detail', models.TextField(verbose_name='商品详情')),
            ],
        ),
        migrations.CreateModel(
            name='HaiyiProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haiyi.AInfo')),
                ('b_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haiyi.BInfo')),
            ],
        ),
    ]
