# Generated by Django 2.2 on 2019-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0007_ainfo_binfo_haiyiproduct_thirdpartyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='haiyiproduct',
            name='name',
            field=models.TextField(null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='thirdpartyproduct',
            name='source',
            field=models.TextField(null=True, verbose_name='商品来源'),
        ),
    ]
