# Generated by Django 2.1.4 on 2018-12-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0007_auto_20181226_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsfile',
            name='wrong_rows',
            field=models.TextField(default='', null=True),
        ),
    ]
