# Generated by Django 2.1.4 on 2018-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0008_auto_20181226_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsfile',
            name='wrong_rows',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
