# Generated by Django 2.2 on 2019-04-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0008_auto_20190427_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haiyiproduct',
            name='a_info',
        ),
        migrations.RemoveField(
            model_name='haiyiproduct',
            name='b_info',
        ),
        migrations.AddField(
            model_name='ainfo',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haiyi.HaiyiProduct'),
        ),
        migrations.AddField(
            model_name='binfo',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haiyi.HaiyiProduct'),
        ),
    ]
