# Generated by Django 2.2.4 on 2019-08-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0007_ainfo_binfo_haiyiproduct_thirdpartyproduct'),
        ('haiyi', '0009_auto_20181226_1708'),
    ]

    operations = [
    ]
