# Generated by Django 3.1.5 on 2021-01-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0009_auto_20190427_0836'),
        ('haiyi', '0010_merge_20190825_0933'),
    ]

    operations = [
    ]
