# Generated by Django 3.1.7 on 2021-03-14 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0009_auto_20190427_0836'),
        ('haiyi', '0010_merge_20190825_0933'),
    ]

    operations = [
    ]
