# Generated by Django 3.2 on 2021-04-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0011_merge_20210130_1530'),
        ('haiyi', '0011_merge_20210314_0250'),
    ]

    operations = [
    ]
