# Generated by Django 2.2.7 on 2021-04-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiyi', '0012_merge_20210411_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdDialogFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='upload/', verbose_name='话术文件')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('dialog_count', models.IntegerField(default=0, verbose_name='话术总条数')),
                ('error', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ainfo',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='binfo',
            name='pid',
        ),
        migrations.DeleteModel(
            name='ThirdPartyProduct',
        ),
        migrations.AddField(
            model_name='haiyiproduct',
            name='uploader',
            field=models.IntegerField(default='管理员', verbose_name='管理员'),
        ),
        migrations.DeleteModel(
            name='AInfo',
        ),
        migrations.DeleteModel(
            name='BInfo',
        ),
    ]
