version: '3'
#
#volumes:
#  postgres_data_local: {}
#  postgres_backup_local: {}

services:
  django: &django
    container_name: django_haiyi
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app
    env_file: .env
    command: /gunicorn.sh
    #command: ["sleep", "1d"]
    restart: always

  postgres:
    container_name: postgres_haiyi
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - ./scantistdb_data_local:/var/lib/scantistdb/data
      - ./scantistdb_backup_local:/backups
    env_file:
      - .env
    ports:
      - "5432:5432"
    privileged: true

  nginx-proxy:
    image: neilpang/nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./compose/config/nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./static/:/static/
      - ./home:/var/www/html
      - ./nginx.tmpl:/app/nginx.tmpl
    env_file:
      - .env
